//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Schedule.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class StudentSet
    {
        public StudentSet()
        {
            this.CourseSet = new HashSet<CourseSet>();
        }
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string FIO { get; set; }
        [DataMember]
        public Nullable<int> Grade { get; set; }

        public virtual ICollection<CourseSet> CourseSet { get; set; }

        public StudentSet(int id, string fio, int grade)
        {
            Id = id;
            FIO = fio;
            Grade = grade;
            CourseSet = new HashSet<CourseSet>();
        }

        public void AddCourse(CourseSet addon)
        {
            CourseSet.Add(addon);
        }

        public void UpdateStudentSet(string fio, int grade)
        {
            FIO = fio;
            Grade = grade;
        }
    }
}
